# https://taskfile.dev

version: "3"

vars:
  TMP_DIR: ./tmp
  SSH_DIR: ./ssh
  IMG_URL: https://share.lv426.space/jammy-server-cloudimg-amd64.img
  #IMG_URL: #https://mirror.yandex.ru/ubuntu-cloud-images/jammy/current/jammy-server-cloudimg-amd64.img
  IMG_NAME: base.img
  IMG_PATH: "{{.TMP_DIR}}/{{.IMG_NAME}}"
  CLOUDINIT_ISO_NAME: cidata.iso
  CLOUDINIT_ISO_PATH: "{{.TMP_DIR}}/{{.CLOUDINIT_ISO_NAME}}"
  CLOUDINIT_PATH: "./cloudinit"
  VM_NAME: vm
  VM_DISK_PATH: "{{.TMP_DIR}}/{{.VM_NAME}}.img"
  VM_DISK_COMPRESSED_PATH: "{{.TMP_DIR}}/{{.VM_NAME}}-compressed.img"

includes:
  docker:
    taskfile: Taskfile.docker.yml
  ansible:
    taskfile: Taskfile.ansible.yml

tasks:
  tmp:
    cmds:
      - mkdir -p {{.TMP_DIR}}
      - mkdir -p {{.SSH_DIR}}
    status:
      - test -d "{{.TMP_DIR}}"
      - test -d "{{.SSH_DIR}}"

  ssh-gen:
    deps:
      - tmp
    cmds:
      - for: [meta, user, vendor]
        cmd: yes | ssh-keygen -t rsa -b 1024 -f {{ .SSH_DIR }}/{{ .ITEM }}-data -N "" -C "{{ .ITEM }}-data" -v
    status:
      - test -f "{{ .SSH_DIR }}/meta-data"
      - test -f "{{ .SSH_DIR }}/user-data"
      - test -f "{{ .SSH_DIR }}/vendor-data"

  ssh:
    vars:
      VM_IP_ADDR:
        sh: |
          virsh domifaddr {{.VM_NAME}} | grep ipv4 | awk '/ipv4/ {split($4, ip, "/"); print ip[1]}'
    cmds:
      - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cloud@{{.VM_IP_ADDR}} -i {{.SSH_DIR}}/user-data

  cloud-init-update-sshkeys:
    vars:
      USER_DATA:
        sh: cat {{ .SSH_DIR }}/user-data.pub
      VENDOR_DATA:
        sh: cat {{ .SSH_DIR }}/vendor-data.pub
      META_DATA:
        sh: cat {{ .SSH_DIR }}/meta-data.pub
    cmds:
    - sed -i 's|ssh-rsa [^ ]* user-data|{{ .USER_DATA }}|g' {{ .CLOUDINIT_PATH }}/*
    - sed -i 's|ssh-rsa [^ ]* vendor-data|{{ .VENDOR_DATA }}|g' {{ .CLOUDINIT_PATH }}/*
    - sed -i 's|ssh-rsa [^ ]* meta-data|{{ .META_DATA }}|g' {{ .CLOUDINIT_PATH }}/*


  image-info:
    cmds:
      - qemu-img info {{.IMG_PATH}}

  image-get-base:
    deps:
      - tmp
    cmds:
      - curl -L {{.IMG_URL}} -o {{.IMG_PATH}}
      - task: image-info
    status:
      - test -f "{{.IMG_PATH}}"

  image-backup:
    cmds:
      - cp -vf {{.IMG_PATH}} {{.IMG_PATH}}.backup

  image-restore:
    cmds:
      - cp -vf {{.IMG_PATH}}.backup {{.IMG_PATH}}

  cloud-init:
    cmds:
      - rm -rf {{.CLOUDINIT_ISO_PATH}}
      - genisoimage -output {{.CLOUDINIT_ISO_PATH}} -fU -V cidata -r -J {{.CLOUDINIT_PATH}}/user-data {{.CLOUDINIT_PATH}}/meta-data {{.CLOUDINIT_PATH}}/vendor-data
    sources:
      - "{{ .CLOUDINIT_PATH }}/*"
    generates:
      - "{{ .CLOUDINIT_ISO_PATH }}"

  vm-disk:
    cmds:
      - cp -vf {{.IMG_PATH}} {{.VM_DISK_PATH}}
    status:
      - test -f "{{.VM_DISK_PATH}}"

  vm-disk-info:
    cmds:
      - qemu-img info {{.VM_DISK_PATH}}

  vm-disk-resize:
    cmds:
      - qemu-img resize {{.VM_DISK_PATH}} +10G
      - task: vm-disk-info

  vm-disk-compress:
    cmds:
      - sudo virt-sparsify --compress {{.VM_DISK_PATH}} {{.VM_DISK_COMPRESSED_PATH}}
    status:
      - test -f "{{.VM_DISK_COMPRESSED_PATH}}"

  vm-run:
    deps:
      - cloud-init
    cmds:
      - |
        # #--graphics none \
        virt-install \
        --name {{.VM_NAME}} \
        --os-variant ubuntu22.04 \
        --ram 1024 \
        --vcpus=1 \
        --disk path={{.VM_DISK_PATH}},format=qcow2,bus=virtio \
        --disk path={{.CLOUDINIT_ISO_PATH}},device=cdrom,bus=sata \
        --network network=default,model=virtio \
        --import \
        --graphics vnc,listen=0.0.0.0 \
        --noautoconsole \
        --console pty,target_type=virtio \
        --serial pty \
        --virt-type kvm

  vm:
    cmds:
      - task: ssh-gen
      - task: image-get-base
      - task: vm-disk
      - task: vm-run
      #- task: ansible-inventory

  vm-reboot:
    cmds:
      - virsh reboot --domain {{.VM_NAME}} || true


  vm-stop:
    cmds:
      - virsh shutdown --domain {{.VM_NAME}} || true

  vm-force-stop:
    cmds:
      - virsh destroy --domain {{.VM_NAME}} || true

  vm-start:
    cmds:
      - virsh start --domain {{.VM_NAME}} || true

  vm-kill:
    cmds:
      - virsh destroy --domain {{.VM_NAME}} || true
      - virsh undefine --domain {{.VM_NAME}} || true
      - rm -rf {{.VM_DISK_PATH}}

  vm-ip:
    vars:
      VM_IP_ADDR:
        sh: |
          virsh domifaddr {{.VM_NAME}} | grep ipv4 | awk '/ipv4/ {split($4, ip, "/"); print ip[1]}'
    cmds:
      - echo "{{.VM_IP_ADDR}}"

  con:
   cmds:
   - virsh console --domain {{.VM_NAME}}

  vnc:
    cmds:
      - virsh vncdisplay {{.VM_NAME}}

  clean:
    cmds:
      - task: vm-kill

  clean-all:
    cmds:
      - task: vm-kill
      - rm -rf {{.TMP_DIR}}
